### ISSUE TITLE
If top panel has been added, resetting bottom panel wipes top panel

### ISSUE THREAD

**Issue by Ferryfolk** [linuxmint/linuxmint#177]
Tested on Mate system upgraded from 19.2.

**Comment by xenopeek** [comment]
This is already reported to mate-panel here: https://github.com/mate-desktop/mate-panel/issues/955. As answered there, multiple panels are still one instance of mate-panel so resetting resets all panels.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-panel/pull/1116 has just been submitted that should fix this

**Comment by Ferryfolk** [comment]
This does not fix the issue. The point is that user may wish to reset just one panel not **all** panels.

**Comment by lukefromdc** [comment]
What this does fix is the user confusion (and possible trap) of thinking "Reset Panel" means reset ONLY the panel the dialog is called from when it actually resets all panels. To reset just one panel would require a major rewrite beyond my ability, as all panels run in one process
